# Import Libraries

In [1]:
import pandas as pd
import numpy as np
from datetime import date

In [2]:
TRAIN = '/media/maria/2TB Monster driv/PrecisionFDA/train/'
TEST = '/media/maria/2TB Monster driv/PrecisionFDA/test/'

In [3]:
pd.options.mode.chained_assignment = None  # default='warn'

# Read Data

## Helper functions

In [4]:
#Function to read the tables and get the data before 2020, as this was removed from the 
#test set

In [5]:
def Read_table_before_2020(input_table, DATE):
    table = pd.read_csv(TRAIN + input_table)
    if input_table == 'encounters.csv':
        table = table.loc[pd.to_datetime(table[DATE]) <= pd.Timestamp(year= 2019, month =12, day= 31, tz='US/Eastern')]   
    else:
        table = table.loc[pd.to_datetime(table[DATE]) <= pd.Timestamp(2019, 12, 31)]
    
    return table

In [6]:
#Helper function to generate the frequency counts of the longitudinal tables

In [7]:
def Pivot_table_counts(table, column='DESCRIPTION', value='ENCOUNTER'):
    pivot = pd.pivot_table(table, values=value, index=['PATIENT'],
                       columns=[column], aggfunc=len, fill_value=0)
    pivot['Id'] = pivot.index
    return pivot

In [8]:
#Helper function to generate the observations dataset

In [9]:
def Get_observations(observation):
    table = observations_tmp.loc[(observations_tmp.DESCRIPTION==observation)]
    table['VALUE'] = pd.to_numeric(table['VALUE']) 
    Pivot_table = pd.pivot_table(table, values='VALUE', index=['PATIENT'],
                        aggfunc=np.mean, fill_value=0)
    Pivot_table.columns = [observation]
    #Pivot_table['Id'] = Pivot_table.index
    
    table = observations_t.loc[(observations_t.DESCRIPTION==observation)]
    table['VALUE'] = pd.to_numeric(table['VALUE']) 
    Pivot_table_t = pd.pivot_table(table, values='VALUE', index=['PATIENT'],
                        aggfunc=np.mean, fill_value=0)
    Pivot_table_t.columns = [observation]
    #Pivot_table_t['Id'] = Pivot_table_t.index    
    
    return Pivot_table, Pivot_table_t

In [10]:
def Get_observations_categorical(observation):
    table = observations_tmp.loc[(observations_tmp.DESCRIPTION==observation)]
    
    Pivot_table = pd.pivot_table(table, columns='VALUE', index=['PATIENT'], values='CODE',
                    aggfunc=len, fill_value=0)
    
    table = observations_t.loc[(observations_t.DESCRIPTION==observation)]
    
    Pivot_table_t = pd.pivot_table(table, columns='VALUE', index=['PATIENT'], values='CODE',
                    aggfunc=len, fill_value=0) 
    
    return Pivot_table, Pivot_table_t

## Read Train Data

In [11]:
allergies = Read_table_before_2020('allergies.csv', 'START')

In [12]:
careplans = Read_table_before_2020('careplans.csv', 'START')

In [13]:
conditions = Read_table_before_2020('conditions.csv', 'START')

In [14]:
devices = Read_table_before_2020('devices.csv', 'START')

In [15]:
encounters = Read_table_before_2020('encounters.csv', 'START')

In [16]:
imaging_studies = Read_table_before_2020('imaging_studies.csv', 'DATE')

In [17]:
immunizations = Read_table_before_2020('immunizations.csv', 'DATE')

In [18]:
medications = Read_table_before_2020('medications.csv', 'START')

In [19]:
observations = Read_table_before_2020('observations.csv', 'DATE')

In [20]:
organizations = pd.read_csv(TRAIN + 'organizations.csv')

In [21]:
patients = pd.read_csv(TRAIN + 'patients.csv')

In [22]:
payers = pd.read_csv(TRAIN + 'payers.csv')

In [23]:
payer_transitions = pd.read_csv(TRAIN + 'payer_transitions.csv')

In [24]:
procedures = Read_table_before_2020('procedures.csv', 'DATE')

In [25]:
providers = pd.read_csv(TRAIN + 'providers.csv')

In [26]:
#Not found in the test set - we will not use it for training
#supplies = pd.read_csv(TRAIN + 'supplies.csv')

## Read Test Data

In [27]:
allergies_t = pd.read_csv(TEST + 'allergies.csv')

In [28]:
careplans_t = pd.read_csv(TEST + 'careplans.csv')

In [29]:
conditions_t = pd.read_csv(TEST + 'conditions.csv')

In [30]:
devices_t = pd.read_csv(TEST + 'devices.csv')

In [31]:
encounters_t = pd.read_csv(TEST + 'encounters.csv')

In [32]:
imaging_studies_t = pd.read_csv(TEST + 'imaging_studies.csv')

In [33]:
immunizations_t = pd.read_csv(TEST + 'immunizations.csv')

In [34]:
medications_t = pd.read_csv(TEST + 'medications.csv')

In [35]:
observations_t = pd.read_csv(TEST + 'observations.csv')

In [36]:
organizations_t = pd.read_csv(TEST + 'organizations.csv')

In [37]:
patients_t = pd.read_csv(TEST + 'patients.csv')

In [38]:
payers_t = pd.read_csv(TEST + 'payers.csv')

In [39]:
payer_transitions_t = pd.read_csv(TEST + 'payer_transitions.csv')

In [40]:
procedures_t = pd.read_csv(TEST + 'procedures.csv')

In [41]:
providers_t = pd.read_csv(TEST + 'providers.csv')

In [42]:
#This file is blank. We will not use it for analysis
#supplies_t = pd.read_csv(TEST + 'supplies.csv')

# Descriptive Statistics

## Allergies

In [43]:
#Compare and check list of allergies is the same in both train and test

In [44]:
len(set(allergies_t.DESCRIPTION)) == len(set(allergies.DESCRIPTION))

True

In [46]:
allergies.shape

(29402, 6)

In [47]:
Allergies = Pivot_table_counts(allergies)

In [48]:
Allergies.describe()

DESCRIPTION,Allergy to bee venom,Allergy to dairy product,Allergy to eggs,Allergy to fish,Allergy to grass pollen,Allergy to mould,Allergy to nut,Allergy to peanuts,Allergy to soya,Allergy to tree pollen,Allergy to wheat,Dander (animal) allergy,House dust mite allergy,Latex allergy,Shellfish allergy
count,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.000000,10896.00000
mean,0.172540,0.038179,0.049284,0.167676,0.254589,0.363803,0.169787,0.188418,0.016887,0.251836,0.045338,0.334526,0.248807,0.068741,0.32801
std,0.377867,0.191637,0.216471,0.373596,0.435650,0.481115,0.375463,0.391063,0.128854,0.434087,0.208053,0.471846,0.432342,0.253024,0.46951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.00000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [49]:
Allergies.shape

(10896, 16)

In [50]:
del allergies

In [51]:
Allergies_t = Pivot_table_counts(allergies_t)

In [52]:
Allergies_t.describe()

DESCRIPTION,Allergy to bee venom,Allergy to dairy product,Allergy to eggs,Allergy to fish,Allergy to grass pollen,Allergy to mould,Allergy to nut,Allergy to peanuts,Allergy to soya,Allergy to tree pollen,Allergy to wheat,Dander (animal) allergy,House dust mite allergy,Latex allergy,Shellfish allergy
count,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000
mean,0.172328,0.036093,0.051309,0.167021,0.266808,0.387827,0.173036,0.188960,0.020524,0.262562,0.047771,0.346426,0.261146,0.069356,0.341472
std,0.377732,0.186556,0.220667,0.373060,0.442370,0.487341,0.378345,0.391546,0.141808,0.440104,0.213318,0.475915,0.439337,0.254103,0.474287
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [53]:
Allergies_t.shape

(2826, 16)

## Careplans

In [54]:
#The items pertaining coronavirus have been deleted from the test set. We need to remove them from 
#the train set

In [56]:
careplans.shape

(353126, 9)

In [57]:
len(set(careplans.DESCRIPTION)) == len(set(careplans_t.DESCRIPTION))

True

In [58]:
#Are there descriptions in the train set not available in the test set? If so --> remove them 
options = np.setdiff1d(list(set(careplans.DESCRIPTION)), list(set(careplans_t.DESCRIPTION)))

In [59]:
list(options)

[]

In [60]:
#Remove from train careplan the description items not in test set
careplans = careplans.loc[~careplans.DESCRIPTION.isin(list(options))]

In [61]:
len(set(careplans.REASONDESCRIPTION)) == len(set(careplans_t.REASONDESCRIPTION))

False

In [62]:
options = np.setdiff1d(list(set(careplans.REASONDESCRIPTION)), list(set(careplans_t.REASONDESCRIPTION)))

In [63]:
options

array(['Fracture of the vertebral column with spinal cord injury',
       'Non-small cell carcinoma of lung  TNM stage 2 (disorder)'],
      dtype='<U69')

In [64]:
#Remove from train careplan the reason description items not in test set
careplans = careplans.loc[~careplans.REASONDESCRIPTION.isin(list(options))]

In [65]:
Careplans = Pivot_table_counts(careplans)

In [66]:
Careplans.describe()

DESCRIPTION,Agreeing on diabetes care plan,Allergic disorder monitoring,Anti-suicide psychotherapy,Asthma self management,Burn care,Cancer care plan,Care Plan,Care plan (record artifact),Chronic obstructive pulmonary disease clinical management plan,Demential management,...,Postoperative care,Psychiatry care plan,Respiratory therapy,Routine antenatal care,Self-care interventions (procedure),Skin condition care,Spinal cord injury rehabilitation,Terminal care,Urinary tract infection care,Wound care
count,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,...,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000,108045.000000
mean,0.000305,0.001897,0.002379,0.039567,0.003267,0.202740,0.337609,0.049081,0.048869,0.050766,...,0.000379,0.196178,0.126012,0.125698,0.157101,0.006238,0.000120,0.087066,0.003230,0.012967
std,0.017474,0.043518,0.048713,0.194940,0.057389,0.410471,0.472897,0.216039,0.215594,0.219520,...,0.019476,0.397106,0.603319,0.715589,0.363898,0.078736,0.010968,0.281932,0.057873,0.116914
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,11.000000,11.000000,1.000000,1.000000,1.000000,1.000000,2.000000,4.000000

In [67]:
Careplans_reason = Pivot_table_counts(careplans, column = 'REASONDESCRIPTION')

In [68]:
Careplans_reason.describe()

REASONDESCRIPTION,Acute bronchitis (disorder),Alzheimer's disease (disorder),Asthma,At risk for suicide (finding),Atopic dermatitis,Attempted suicide - cut/stab,Attempted suicide - suffocation,Bullet wound,Child attention deficit disorder,Childhood asthma,...,Rupture of patellar tendon,Second degree burn,Secondary malignant neoplasm of colon,Smokes tobacco daily,Sprain of ankle,Sprain of wrist,Suicidal deliberate poisoning,Tear of meniscus of knee,Third degree burn,Whiplash injury to neck
count,105179.000000,105179.00000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,...,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000,105179.000000
mean,0.129446,0.04093,0.002168,0.000171,0.005590,0.000456,0.000333,0.000219,0.000447,0.038477,...,0.000780,0.001312,0.003042,0.164120,0.009051,0.004107,0.001654,0.000475,0.000171,0.040474
std,0.611120,0.19813,0.046509,0.015722,0.074561,0.021358,0.018239,0.014786,0.021134,0.192346,...,0.027911,0.036199,0.055075,0.370386,0.099122,0.065572,0.040640,0.021798,0.013081,0.219439
min,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,11.000000,1.00000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,4.000000,3.000000,1.000000,1.000000,1.000000,5.000000

In [69]:
del careplans

In [70]:
# test set doesn't have Infectious disease care plan (record artifact)

In [71]:
Careplans_t = Pivot_table_counts(careplans_t)

In [72]:
Careplans_t.describe()

DESCRIPTION,Agreeing on diabetes care plan,Allergic disorder monitoring,Anti-suicide psychotherapy,Asthma self management,Burn care,Cancer care plan,Care Plan,Care plan (record artifact),Chronic obstructive pulmonary disease clinical management plan,Demential management,...,Postoperative care,Psychiatry care plan,Respiratory therapy,Routine antenatal care,Self-care interventions (procedure),Skin condition care,Spinal cord injury rehabilitation,Terminal care,Urinary tract infection care,Wound care
count,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,...,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000,26993.000000
mean,0.000222,0.001852,0.001852,0.041418,0.003445,0.196051,0.337050,0.051643,0.050087,0.051791,...,0.000185,0.194865,0.129367,0.126144,0.159264,0.006891,0.000037,0.085467,0.003075,0.012114
std,0.014908,0.043000,0.043000,0.199259,0.058597,0.405235,0.472711,0.221309,0.218129,0.221609,...,0.013609,0.396104,0.601946,0.717082,0.365928,0.082725,0.006087,0.279580,0.057339,0.111078
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,11.000000,13.000000,1.000000,1.000000,1.000000,1.000000,2.000000,3.000000

In [73]:
Careplans_reason_t = Pivot_table_counts(careplans_t, column = 'REASONDESCRIPTION')

In [74]:
Careplans_reason_t.describe()

REASONDESCRIPTION,Acute bronchitis (disorder),Alzheimer's disease (disorder),Asthma,At risk for suicide (finding),Atopic dermatitis,Attempted suicide - cut/stab,Attempted suicide - suffocation,Bullet wound,Child attention deficit disorder,Childhood asthma,...,Rupture of patellar tendon,Second degree burn,Secondary malignant neoplasm of colon,Smokes tobacco daily,Sprain of ankle,Sprain of wrist,Suicidal deliberate poisoning,Tear of meniscus of knee,Third degree burn,Whiplash injury to neck
count,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,...,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000,26292.000000
mean,0.132816,0.042066,0.002929,0.000266,0.006314,0.000304,0.000114,0.000152,0.000723,0.039594,...,0.000647,0.001255,0.003233,0.165716,0.009851,0.003613,0.001483,0.000342,0.000266,0.042751
std,0.609542,0.200744,0.054039,0.022235,0.079209,0.017441,0.010682,0.012334,0.026873,0.195007,...,0.025420,0.035406,0.056768,0.371832,0.108665,0.060633,0.038486,0.018499,0.016315,0.225082
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,11.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,5.000000,2.000000,1.000000,1.000000,1.000000,3.000000

In [75]:
del careplans_t

In [76]:
Careplans.shape

(108045, 37)

In [77]:
Careplans_reason.shape

(105179, 73)

In [78]:
Careplans.shape

(108045, 37)

In [79]:
Careplans_reason.shape

(105179, 73)

## Conditions

In [80]:
#The following conditions have been removed from the test set!

In [81]:
options = np.setdiff1d(list(set(conditions.DESCRIPTION)), list(set(conditions_t.DESCRIPTION)))

In [82]:
list(options)

['Attempted suicide - cut/stab',
 'Non-small cell carcinoma of lung  TNM stage 2 (disorder)']

In [83]:
conditions_tmp = conditions.loc[~conditions.DESCRIPTION.isin(list(options))]

In [84]:
len(set(conditions_tmp.DESCRIPTION))

157

In [85]:
conditions.shape

(773942, 6)

In [87]:
Conditions =  Pivot_table_counts(conditions_tmp)

In [88]:
Conditions.describe()

DESCRIPTION,Acute Cholecystitis,Acute allergic reaction,Acute bacterial sinusitis (disorder),Acute bronchitis (disorder),Acute respiratory failure (disorder),Acute viral pharyngitis (disorder),Alcoholism,Alzheimer's disease (disorder),Anemia (disorder),Antepartum eclampsia,...,Streptococcal sore throat (disorder),Stroke,Suicidal deliberate poisoning,Suspected lung cancer (situation),Tear of meniscus of knee,Third degree burn,Traumatic brain injury (disorder),Tubal pregnancy,Viral sinusitis (disorder),Whiplash injury to neck
count,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,...,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000,114521.000000
mean,0.000323,0.000253,0.005981,0.041669,0.000131,0.051205,0.120519,0.037591,0.472891,0.001327,...,0.008819,0.073506,0.000044,0.082343,0.000410,0.000157,0.006549,0.030614,0.108190,0.004436
std,0.017972,0.015911,0.080434,0.235720,0.011444,0.279053,0.325569,0.190207,0.499267,0.037120,...,0.098500,0.260967,0.006607,0.274888,0.020254,0.012536,0.080661,0.182463,0.547065,0.067108
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,3.000000,10.000000,1.000000,11.000000,1.000000,1.000000,1.000000,3.000000,...,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,19.000000,3.000000

In [89]:
del conditions_tmp

In [90]:
Conditions_t = Pivot_table_counts(conditions_t)

In [91]:
Conditions_t.describe()

DESCRIPTION,Acute Cholecystitis,Acute allergic reaction,Acute bacterial sinusitis (disorder),Acute bronchitis (disorder),Acute respiratory failure (disorder),Acute viral pharyngitis (disorder),Alcoholism,Alzheimer's disease (disorder),Anemia (disorder),Antepartum eclampsia,...,Streptococcal sore throat (disorder),Stroke,Suicidal deliberate poisoning,Suspected lung cancer (situation),Tear of meniscus of knee,Third degree burn,Traumatic brain injury (disorder),Tubal pregnancy,Viral sinusitis (disorder),Whiplash injury to neck
count,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,...,28671.00000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000,28671.000000
mean,0.000174,0.000140,0.006243,0.043703,0.000035,0.053399,0.119877,0.038576,0.467336,0.001291,...,0.00851,0.072338,0.000035,0.080709,0.000279,0.000244,0.006453,0.029577,0.113006,0.004360
std,0.013205,0.011811,0.080952,0.239916,0.005906,0.288075,0.324824,0.192584,0.498941,0.041321,...,0.09411,0.259051,0.005906,0.272392,0.016702,0.015624,0.080069,0.177857,0.560528,0.065886
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,3.000000,7.000000,1.000000,9.000000,1.000000,1.000000,1.000000,4.000000,...,3.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,16.000000,1.000000

In [92]:
del conditions_t

In [93]:
Conditions.shape

(114521, 158)

In [94]:
Conditions_t.shape

(28671, 158)

## Devices

In [95]:
len(set(devices.DESCRIPTION)) == len(set(devices_t.DESCRIPTION))

True

In [96]:
options = np.setdiff1d(list(set(devices.DESCRIPTION)), list(set(devices_t.DESCRIPTION)))
list(options)

[]

In [98]:
devices = devices.loc[~devices.DESCRIPTION.isin(list(options))]

In [99]:
devices.DESCRIPTION.value_counts()

Implantable defibrillator  device (physical object)    5723
Coronary artery stent (physical object)                3663
Implantable cardiac pacemaker (physical object)        1484
Name: DESCRIPTION, dtype: int64

In [100]:
Devices = Pivot_table_counts(devices)

In [101]:
Devices.describe()

DESCRIPTION,Coronary artery stent (physical object),Implantable cardiac pacemaker (physical object),Implantable defibrillator device (physical object)
count,10534.000000,10534.000000,10534.000000
mean,0.347731,0.140877,0.543288
std,0.476273,0.347911,0.498146
min,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000
75%,1.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000

Negative for non presence as opposed to missing

In [102]:
Devices_t = Pivot_table_counts(devices_t)

In [103]:
Devices_t.describe()

DESCRIPTION,Coronary artery stent (physical object),Implantable cardiac pacemaker (physical object),Implantable defibrillator device (physical object)
count,2630.000000,2630.000000,2630.000000
mean,0.355894,0.123954,0.557795
std,0.478874,0.329592,0.496743
min,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000
75%,1.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000

In [104]:
del devices, devices_t

In [105]:
Devices.shape

(10534, 4)

In [106]:
Devices_t.shape

(2630, 4)

## Encounters

In [108]:
options = np.setdiff1d(list(set(encounters.REASONDESCRIPTION)), list(set(encounters_t.REASONDESCRIPTION)))
options

array(['Non-small cell carcinoma of lung  TNM stage 2 (disorder)',
       'Suicide - suffocation'], dtype='<U69')

In [109]:
encounters_tmp = encounters.loc[~encounters.REASONDESCRIPTION.isin(options)]

In [110]:
len(set(encounters.DESCRIPTION)) == len(set(encounters_t.DESCRIPTION))

False

In [111]:
options = np.setdiff1d(list(set(encounters.DESCRIPTION)), list(set(encounters_t.DESCRIPTION)))
options

array(['Awaiting transplantation of lung (situation)'], dtype='<U70')

In [112]:
encounters_tmp = encounters_tmp.loc[~encounters_tmp.DESCRIPTION.isin(list(options))]

In [113]:
encounters['START'] = pd.to_datetime(encounters.START)

In [114]:
encounters['STOP'] = pd.to_datetime(encounters.STOP)

In [115]:
encounters_t['START'] = pd.to_datetime(encounters_t.START)

In [116]:
encounters_t['STOP'] = pd.to_datetime(encounters_t.STOP)

In [117]:
encounters_tmp.shape

(5702250, 15)

In [118]:
len(encounters.PATIENT.unique())

116361

In [119]:
Encounters = Pivot_table_counts(encounters_tmp, value='CODE')

In [120]:
Encounters.describe()

DESCRIPTION,Admission to surgical department,Admission to thoracic surgery department,Allergic disorder follow-up assessment,Allergic disorder initial assessment,Asthma follow-up,Cardiac Arrest,Consultation for treatment,Death Certification,Diagnosis of cystic fibrosis using sweat test and gene test,Discussion about treatment (procedure),...,Postoperative follow-up visit (procedure),Prenatal initial visit,Prenatal visit,Screening surveillance (regime/therapy),Stroke,Telemedicine consultation with patient,Telephone encounter (procedure),Urgent care clinic (procedure),Well child visit (procedure),posttraumatic stress disorder
count,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,...,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000,116361.000000
mean,0.003506,0.001556,0.001641,0.003369,0.038106,0.047808,0.184778,0.216714,0.000327,0.001048,...,0.035983,0.413188,0.269549,0.021322,0.067892,0.149956,0.057408,1.005500,0.727598,0.037117
std,0.059256,0.039409,0.040482,0.057944,0.305938,0.214726,0.583785,0.412008,0.018068,0.032363,...,0.278919,0.983402,0.969218,0.177791,0.255897,4.030317,0.722571,3.096273,2.863937,0.228562
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.000000,1.000000,1.000000,1.000000,13.000000,2.000000,10.000000,1.000000,1.000000,1.000000,...,6.000000,15.000000,14.000000,17.000000,3.000000,236.000000,41.000000,30.000000,25.000000,5.000000

In [121]:
Encounters_reason = Pivot_table_counts(encounters_tmp, column= 'REASONDESCRIPTION', value='CODE')

In [122]:
Encounters_reason.describe()

REASONDESCRIPTION,Acute Cholecystitis,Acute bacterial sinusitis (disorder),Acute bronchitis (disorder),Acute respiratory failure (disorder),Acute viral pharyngitis (disorder),Alzheimer's disease (disorder),Anemia (disorder),Appendicitis,Asthma,At risk for suicide (finding),...,Small cell carcinoma of lung (disorder),Streptococcal sore throat (disorder),Stroke,Sudden Cardiac Death,Suicidal deliberate poisoning,Suicide - firearms,Suspected lung cancer (situation),Third degree burn,Tubal pregnancy,Viral sinusitis (disorder)
count,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,...,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000,108591.000000
mean,0.001077,0.161524,0.235342,0.000138,0.141384,0.035657,0.324207,0.128003,0.037020,0.000193,...,0.022258,0.027811,0.011999,0.014614,0.001676,0.000037,0.093138,0.000258,0.001096,0.358492
std,0.032807,0.439119,0.695225,0.011752,0.424678,0.245410,0.477662,0.489514,0.311448,0.016895,...,0.202007,0.171289,0.108882,0.120004,0.043098,0.006069,0.311578,0.016056,0.033910,0.831594
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,9.000000,11.000000,1.000000,11.000000,4.000000,3.000000,2.000000,14.000000,2.000000,...,2.000000,5.000000,1.000000,1.000000,3.000000,1.000000,3.000000,1.000000,2.000000,19.000000

In [123]:
Encounters_t = Pivot_table_counts(encounters_t, value='CODE')

In [124]:
Encounters_t.describe()

DESCRIPTION,Admission to surgical department,Admission to thoracic surgery department,Allergic disorder follow-up assessment,Allergic disorder initial assessment,Asthma follow-up,Cardiac Arrest,Consultation for treatment,Death Certification,Diagnosis of cystic fibrosis using sweat test and gene test,Discussion about treatment (procedure),...,Postoperative follow-up visit (procedure),Prenatal initial visit,Prenatal visit,Screening surveillance (regime/therapy),Stroke,Telemedicine consultation with patient,Telephone encounter (procedure),Urgent care clinic (procedure),Well child visit (procedure),posttraumatic stress disorder
count,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.00000,29129.000000,...,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000,29129.000000
mean,0.003502,0.002128,0.001922,0.003433,0.040921,0.048234,0.182190,0.216485,0.00024,0.001133,...,0.035429,0.410278,0.274984,0.020976,0.067527,0.129630,0.056439,0.996018,0.750867,0.036870
std,0.059651,0.046087,0.043805,0.058492,0.337264,0.215382,0.574154,0.411856,0.01550,0.033640,...,0.278143,0.968959,0.999406,0.159194,0.254604,3.470154,0.689984,3.078002,2.915294,0.228166
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.000000,1.000000,1.000000,1.000000,13.000000,2.000000,8.000000,1.000000,1.00000,1.000000,...,6.000000,14.000000,11.000000,5.000000,2.000000,207.000000,31.000000,30.000000,24.000000,6.000000

In [125]:
Encounters_reason_t = Pivot_table_counts(encounters_t, column= 'REASONDESCRIPTION', value='CODE')

In [126]:
Encounters_reason_t.describe()

REASONDESCRIPTION,Acute Cholecystitis,Acute bacterial sinusitis (disorder),Acute bronchitis (disorder),Acute respiratory failure (disorder),Acute viral pharyngitis (disorder),Alzheimer's disease (disorder),Anemia (disorder),Appendicitis,Asthma,At risk for suicide (finding),...,Small cell carcinoma of lung (disorder),Streptococcal sore throat (disorder),Stroke,Sudden Cardiac Death,Suicidal deliberate poisoning,Suicide - firearms,Suspected lung cancer (situation),Third degree burn,Tubal pregnancy,Viral sinusitis (disorder)
count,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,...,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.000000,27144.00000,27144.000000,27144.000000,27144.000000
mean,0.000663,0.164788,0.239390,0.000037,0.145078,0.037651,0.316645,0.123490,0.040746,0.000368,...,0.020373,0.027925,0.012342,0.014110,0.001474,0.000037,0.09177,0.000368,0.000995,0.369953
std,0.025743,0.443960,0.692656,0.006070,0.429826,0.253446,0.473263,0.481392,0.348519,0.025749,...,0.193637,0.167643,0.110407,0.117946,0.039309,0.006070,0.31071,0.019191,0.034854,0.846223
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000
max,1.000000,6.000000,11.000000,1.000000,9.000000,4.000000,3.000000,2.000000,13.000000,3.000000,...,2.000000,3.000000,1.000000,1.000000,2.000000,1.000000,3.00000,1.000000,2.000000,16.000000

In [127]:
del encounters_tmp, encounters_t

In [128]:
Encounters.shape

(116361, 54)

This is supposed to be veterans data. Why do we have well child visits and not an inconsequential amount?

## Imaging Studies

In [129]:
main_list = np.setdiff1d(list(set(imaging_studies.BODYSITE_DESCRIPTION)), 
                         list(set(imaging_studies_t.BODYSITE_DESCRIPTION)))
main_list

array([], dtype='<U44')

In [130]:
main_list = np.setdiff1d(list(set(imaging_studies.MODALITY_DESCRIPTION)), 
                         list(set(imaging_studies_t.MODALITY_DESCRIPTION)))
main_list

array([], dtype='<U20')

In [132]:
Imaging_studies = Pivot_table_counts(imaging_studies, column= 'BODYSITE_DESCRIPTION')

In [133]:
#MODALITY_DESCRIPTION

In [134]:
Imaging_studies_mod = Pivot_table_counts(imaging_studies, column= 'MODALITY_DESCRIPTION')

In [135]:
Imaging_studies_mod.describe()

MODALITY_DESCRIPTION,Computed Radiography,Computed Tomography,Digital Radiography,Ultrasound
count,13096.000000,13096.000000,13096.000000,13096.000000
mean,0.583308,1.232132,1.012217,1.410889
std,0.597379,3.858972,0.656279,1.300924
min,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000
50%,1.000000,0.000000,1.000000,2.000000
75%,1.000000,0.000000,1.000000,2.000000
max,4.000000,29.000000,7.000000,8.000000

In [136]:
Imaging_studies_t = Pivot_table_counts(imaging_studies_t, column= 'BODYSITE_DESCRIPTION')

In [137]:
Imaging_studies_mod_t = Pivot_table_counts(imaging_studies_t, column= 'MODALITY_DESCRIPTION')

In [138]:
Imaging_studies.shape

(13096, 13)

In [139]:
Imaging_studies_mod.shape

(13096, 5)

In [140]:
Imaging_studies_t.shape

(3252, 13)

In [141]:
Imaging_studies_mod_t.shape

(3252, 5)

In [142]:
del imaging_studies, imaging_studies_t

SOP description less important

## Immunizations

In [143]:
main_list = np.setdiff1d(list(set(immunizations.DESCRIPTION)), 
                         list(set(immunizations_t.DESCRIPTION)))
main_list

array([], dtype='<U50')

In [145]:
immunizations.DESCRIPTION.value_counts()

Influenza  seasonal  injectable  preservative free    75548
Td (adult) preservative free                           8585
pneumococcal polysaccharide vaccine  23 valent         2153
zoster                                                 1756
Hep A  adult                                           1708
Pneumococcal conjugate PCV 13                          1514
Hep B  adult                                           1336
meningococcal MCV4P                                     817
IPV                                                     397
Hib (PRP-OMP)                                           173
Hep B  adolescent or pediatric                          113
MMR                                                     102
varicella                                                49
DTaP                                                     37
HPV  quadrivalent                                        35
Hep A  ped/adol  2 dose                                  16
Tdap                                                     16
Name: DESCRIPTION, dtype: int64

In [146]:
Immunizations = Pivot_table_counts(immunizations)

In [147]:
Immunizations.describe()

DESCRIPTION,DTaP,HPV quadrivalent,Hep A adult,Hep A ped/adol 2 dose,Hep B adolescent or pediatric,Hep B adult,Hib (PRP-OMP),IPV,Influenza seasonal injectable preservative free,MMR,Pneumococcal conjugate PCV 13,Td (adult) preservative free,Tdap,meningococcal MCV4P,pneumococcal polysaccharide vaccine 23 valent,varicella,zoster
count,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000,74553.000000
mean,0.000496,0.000469,0.022910,0.000215,0.001516,0.017920,0.002320,0.005325,1.013346,0.001368,0.020308,0.115153,0.000215,0.010959,0.028879,0.000657,0.023554
std,0.028600,0.022867,0.152547,0.014648,0.057540,0.139464,0.065985,0.113647,0.215796,0.036964,0.141052,0.319209,0.014648,0.104109,0.167467,0.025629,0.157043
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3.000000,2.000000,2.000000,1.000000,3.000000,3.000000,3.000000,3.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000

In [148]:
Immunizations.shape

(74553, 18)

In [149]:
Immunizations_t = Pivot_table_counts(immunizations_t)

In [150]:
Immunizations_t.shape

(18834, 18)

## Medications

In [151]:
options_ = np.setdiff1d(list(set(medications_t.DESCRIPTION)), 
                         list(set(medications.DESCRIPTION)))
list(options_)

['Kalydeco 150 MG Oral Tablet']

In [152]:
options = np.setdiff1d(list(set(medications.DESCRIPTION)), 
                         list(set(medications_t.DESCRIPTION)))
list(options)

['Doxycycline Monohydrate 100 MG Oral Tablet',
 'Lorazepam 2 MG/ML Injectable Solution',
 'ado-trastuzumab emtansine 100 MG Injection',
 'atomoxetine 100 MG Oral Capsule',
 'desflurane 1000 MG/ML Inhalation Solution',
 'neratinib 40 MG Oral Tablet',
 'sevoflurane 1000 MG/ML Inhalant Solution']

In [153]:
medications = medications.loc[~medications.DESCRIPTION.isin(list(options) + list(options_))]

In [154]:
medications_t = medications_t.loc[~medications_t.DESCRIPTION.isin(list(options) + list(options_))]

In [155]:
Medications = pd.pivot_table(medications, values='DISPENSES', index=['PATIENT'],
                       columns=['DESCRIPTION'], aggfunc=np.sum, fill_value=0)

In [156]:
Medications.describe()

DESCRIPTION,0.25 ML Leuprolide Acetate 30 MG/ML Prefilled Syringe,1 ML DOCEtaxel 20 MG/ML Injection,1 ML Epinephrine 1 MG/ML Injection,1 ML Epoetin Alfa 4000 UNT/ML Injection [Epogen],1 ML Morphine Sulfate 5 MG/ML Injection,1 ML denosumab 60 MG/ML Prefilled Syringe,1 ML heparin sodium porcine 5000 UNT/ML Injection,1 ML medroxyPROGESTERone acetate 150 MG/ML Injection,1 ML medroxyprogesterone acetate 150 MG/ML Injection,10 ML Alfentanil 0.5 MG/ML Injection,...,exemestane 25 MG Oral Tablet,ferrous sulfate 325 MG Oral Tablet,insulin human isophane 70 UNT/ML / Regular Insulin Human 30 UNT/ML Injectable Suspension [Humulin],letrozole 2.5 MG Oral Tablet,palbociclib 100 MG Oral Capsule,predniSONE 20 MG Oral Tablet,predniSONE 5 MG Oral Tablet,pregabalin 100 MG Oral Capsule,remifentanil 2 MG Injection,ribociclib 200 MG Oral Tablet
count,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,...,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000,104625.000000
mean,17.403546,17.403546,0.008210,1.102930,0.000354,0.000516,0.000401,0.054585,0.164454,0.000048,...,0.000153,24.209137,47.879302,0.000105,0.000258,0.000210,0.000277,0.000898,0.000162,0.000373
std,49.052419,49.052419,0.090344,10.250564,0.018802,0.031219,0.020032,0.832701,1.731815,0.006913,...,0.012365,102.353929,120.962850,0.010253,0.016062,0.044372,0.016647,0.035509,0.012746,0.019303
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,301.000000,301.000000,2.000000,120.000000,1.000000,2.000000,1.000000,36.000000,66.000000,1.000000,...,1.000000,986.000000,731.000000,1.000000,1.000000,14.000000,1.000000,3.000000,1.000000,1.000000

In [157]:
Medications['Id'] = Medications.index

In [158]:
Medications_t = pd.pivot_table(medications_t, values='DISPENSES', index=['PATIENT'],
                       columns=['DESCRIPTION'], aggfunc=np.sum, fill_value=0)

In [159]:
Medications_t['Id'] = Medications_t.index

In [160]:
Medications_t.describe()

DESCRIPTION,0.25 ML Leuprolide Acetate 30 MG/ML Prefilled Syringe,1 ML DOCEtaxel 20 MG/ML Injection,1 ML Epinephrine 1 MG/ML Injection,1 ML Epoetin Alfa 4000 UNT/ML Injection [Epogen],1 ML Morphine Sulfate 5 MG/ML Injection,1 ML denosumab 60 MG/ML Prefilled Syringe,1 ML heparin sodium porcine 5000 UNT/ML Injection,1 ML medroxyPROGESTERone acetate 150 MG/ML Injection,1 ML medroxyprogesterone acetate 150 MG/ML Injection,10 ML Alfentanil 0.5 MG/ML Injection,...,exemestane 25 MG Oral Tablet,ferrous sulfate 325 MG Oral Tablet,insulin human isophane 70 UNT/ML / Regular Insulin Human 30 UNT/ML Injectable Suspension [Humulin],letrozole 2.5 MG Oral Tablet,palbociclib 100 MG Oral Capsule,predniSONE 20 MG Oral Tablet,predniSONE 5 MG Oral Tablet,pregabalin 100 MG Oral Capsule,remifentanil 2 MG Injection,ribociclib 200 MG Oral Tablet
count,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,...,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000,26310.000000
mean,16.829571,16.829571,0.008742,1.145192,0.000190,0.000152,0.000190,0.066021,0.153630,0.000038,...,0.000114,22.727594,47.340669,0.000114,0.000228,0.000114,0.000152,0.000380,0.000038,0.000342
std,48.413107,48.413107,0.093090,10.413346,0.013785,0.017437,0.013785,0.902784,1.691865,0.006165,...,0.010678,99.154088,120.650650,0.010678,0.015100,0.010678,0.012329,0.019492,0.006165,0.018492
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,301.000000,301.000000,1.000000,120.000000,1.000000,2.000000,1.000000,24.000000,59.000000,1.000000,...,1.000000,960.000000,681.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [161]:
Medications.shape

(104625, 162)

In [162]:
Medications_t.shape

(26310, 162)

In [163]:
del medications, medications_t

In [164]:
#sum over dispenses lifetime to get an idea of the severity of the condition
#maybe later- number of antibiotics, number of blood pressure etc..

## Observations

In [165]:
options = np.setdiff1d(list(set(observations.DESCRIPTION)), 
                         list(set(observations_t.DESCRIPTION)))
list(options)

['Activities of daily living score [KOOS]',
 'PROMIS-29 Anxiety score',
 'PROMIS-29 Depression score',
 'PROMIS-29 Fatigue score',
 'PROMIS-29 Pain interference score',
 'PROMIS-29 Physical function score',
 'PROMIS-29 Satisfaction with participation in social roles score',
 'PROMIS-29 Sleep disturbance score',
 'Pain score [KOOS]',
 'Quality of life score [KOOS]',
 'Sport-recreation score [KOOS]',
 'Symptoms score [KOOS]',
 'VR-36 Bodily pain (BP) score - oblique method',
 'VR-36 General health (GH) score - oblique method',
 'VR-36 Mental health (MH) score - oblique method',
 'VR-36 Physical functioning (PF) score - oblique method',
 'VR-36 Role emotion (RE) score - oblique method',
 'VR-36 Role physical (RP) score - oblique method',
 'VR-36 Social functioning (SF) score - oblique method',
 'VR-36 Vitality (VT) score - oblique method']

In [166]:
observations_tmp = observations.loc[~observations.DESCRIPTION.isin(list(options))]

In [167]:
#Remove observations after 2020

observations_tmp.shape

(5763395, 8)

In [168]:
#This was removed from the test set - can't train with it

In [169]:
observations_tmp = observations_tmp.loc[pd.to_datetime(observations_tmp.DATE) <= pd.Timestamp(2019, 12, 31)]

In [170]:
#FE for systolic and diastolic BP, max, min, average, last, weighted average, (body weight)

In [172]:
#To select which features to use
pd.DataFrame(observations.DESCRIPTION.value_counts()).to_csv('observations_counts.csv')

In [173]:
SBP_table, SBP_table_t = Get_observations('Systolic Blood Pressure')

In [174]:
DBP, DBP_t = Get_observations('Diastolic Blood Pressure')
HR, HR_t = Get_observations('Heart rate')
RR, RR_t = Get_observations('Respiratory rate')
Weight, Weight_t = Get_observations('Body Weight')
Oxygen, Oxygen_t = Get_observations('Oxygen saturation in Arterial blood')
Pain, Pain_t = Get_observations('Pain severity - 0-10 verbal numeric rating [Score] - Reported')
Temperature, Temperature_t= Get_observations('Body temperature')
Glomerular, Glomerular_t = Get_observations('Glomerular filtration rate/1.73 sq M.predicted')
Alkaline, Alkaline_t = Get_observations('Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma')
Alanine, Alanine_t = Get_observations('Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma')
Albumin, Albumin_t = Get_observations('Albumin [Mass/volume] in Serum or Plasma')
Aspartate, Aspartate_t = Get_observations('Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma')
Protein, Protein_t = Get_observations('Protein [Mass/volume] in Serum or Plasma')
Bilirubin, Bilirubin_t = Get_observations('Bilirubin.total [Mass/volume] in Serum or Plasma')
Hemoglobin, Hemoglobin_t = Get_observations('Hemoglobin [Mass/volume] in Blood')
MCV, MCV_t = Get_observations('MCV [Entitic volume] by Automated count')
MCHC, MCHC_t = Get_observations('MCHC [Mass/volume] by Automated count')
Platelets, Platelets_t = Get_observations('Platelets [#/volume] in Blood by Automated count')
MCH, MCH_t = Get_observations('MCH [Entitic mass] by Automated count')
Hematocrit, Hematocrit_t = Get_observations('Hematocrit [Volume Fraction] of Blood by Automated count')
Leukocytes, Leukocytes_t = Get_observations('Leukocytes [#/volume] in Blood by Automated count')
Erythrocytes, Erythrocytes_t = Get_observations('Erythrocytes [#/volume] in Blood by Automated count')
Carbon, Carbon_t= Get_observations('Carbon Dioxide')
Calcium, Calcium_t= Get_observations('Calcium')
Chloride, Chloride_t= Get_observations('Chloride')
Potassium, Potassium_t= Get_observations('Potassium')
Urea, Urea_t = Get_observations('Urea Nitrogen')
Creatinine, Creatinine_t= Get_observations('Creatinine')
Sodium, Sodium_t = Get_observations('Sodium')
Glucose, Glucose_t= Get_observations('Glucose')
Height, Height_t = Get_observations('Body Height')

In [175]:
BMI, BMI_t = Get_observations('Body Mass Index')
Low_Density_Cholesterol, Low_Density_Cholesterol_t = Get_observations('Low Density Lipoprotein Cholesterol')
High_Density_Cholesterol, High_Density_Cholesterol_t = Get_observations('High Density Lipoprotein Cholesterol')
Triglycerides, Triglycerides_t = Get_observations('Triglycerides')
Total_Cholesterol, Total_Cholesterol_t = Get_observations('Total Cholesterol')
Hemoglobin, Hemoglobin_t = Get_observations('Hemoglobin A1c/Hemoglobin.total in Blood')
Weight_difference, Weight_difference_t = Get_observations('Weight difference [Mass difference] --pre dialysis - post dialysis')
Microalbumin, Microalbumin_t = Get_observations('Microalbumin Creatinine Ratio')
GFR, GFR_t = Get_observations('Estimated Glomerular Filtration Rate')
DALY, DALY_t = Get_observations('DALY')
QOLS, QOLS_t = Get_observations('QOLS')
QALY, QALY_t = Get_observations('QALY')
Globulin, Globulin_t = Get_observations('Globulin [Mass/volume] in Serum by calculation')
Platelet_mean, Platelet_mean_t = Get_observations('Platelet mean volume [Entitic volume] in Blood by Automated count')
Platelet_distribution, Platelet_distribution_t = Get_observations('Platelet distribution width [Entitic volume] in Blood by Automated count')
Erythrocyte, Erythrocyte_t = Get_observations('Erythrocyte distribution width [Entitic volume] by Automated count')
pH_Urine, pH_Urine_t = Get_observations('pH of Urine by Test strip')
Ketones, Ketones_t = Get_observations('Ketones [Mass/volume] in Urine by Test strip')
BilirubinMass, BilirubinMass_t = Get_observations('Bilirubin.total [Mass/volume] in Urine by Test strip')
Glucose_Mass, Glucose_Mass_t = Get_observations('Glucose [Mass/volume] in Urine by Test strip')
Specific_gravity, Specific_gravity_t = Get_observations('Specific gravity of Urine by Test strip')
Protein_MassUrine, Protein_MassUrine_t = Get_observations('Protein [Mass/volume] in Urine by Test strip')

In [176]:
ProstateAg, ProstateAg_t = Get_observations('Prostate specific Ag [Mass/volume] in Serum or Plasma')
Left_ventricular, Left_ventricular_t = Get_observations('Left ventricular Ejection fraction')
FEV1_FVC, FEV1_FVC_t = Get_observations('FEV1/FVC')

In [177]:
frames = [SBP_table, DBP,HR, RR, Weight, Oxygen,Pain, Temperature, Glomerular, Alkaline, Alanine,
         Albumin, Aspartate, Protein, Bilirubin, Hemoglobin, MCV, MCHC, Platelets, MCH, Hematocrit,
         Leukocytes, Erythrocytes, Carbon, Calcium, Chloride, Potassium, Urea, Creatinine, Sodium,
         Glucose, Height, BMI, Low_Density_Cholesterol, High_Density_Cholesterol, Triglycerides, 
         Total_Cholesterol, Hemoglobin, Weight_difference, Microalbumin, GFR, DALY, QOLS, QALY, 
         Globulin, Platelet_mean, Platelet_distribution,
         Erythrocyte, pH_Urine, Ketones, BilirubinMass, Glucose_Mass, Specific_gravity, Protein_MassUrine,
         ProstateAg, Left_ventricular, FEV1_FVC]


Observations = pd.concat(frames, axis=1, sort=True)
Observations['Id'] = Observations.index
Observations.describe()

,Systolic Blood Pressure,Diastolic Blood Pressure,Heart rate,Respiratory rate,Body Weight,Oxygen saturation in Arterial blood,Pain severity - 0-10 verbal numeric rating [Score] - Reported,Body temperature,Glomerular filtration rate/1.73 sq M.predicted,Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma,...,Erythrocyte distribution width [Entitic volume] by Automated count,pH of Urine by Test strip,Ketones [Mass/volume] in Urine by Test strip,Bilirubin.total [Mass/volume] in Urine by Test strip,Glucose [Mass/volume] in Urine by Test strip,Specific gravity of Urine by Test strip,Protein [Mass/volume] in Urine by Test strip,Prostate specific Ag [Mass/volume] in Serum or Plasma,Left ventricular Ejection fraction,FEV1/FVC
count,79139.000000,79139.000000,79114.000000,79114.000000,79114.000000,6842.000000,79990.000000,5805.000000,23848.000000,23512.000000,...,17964.000000,3950.000000,3950.000000,3950.000000,3950.000000,3950.0,3950.000000,9722.000000,5321.000000,4548.000000
mean,122.290727,80.924524,80.058156,13.995741,82.286049,75.042811,2.170827,37.629076,54.095721,80.119933,...,42.503851,5.997364,9.971244,0.852644,1.508971,1.0,327.057769,2.904001,39.534035,35.561712
std,14.517261,7.302765,10.345604,1.025100,14.238590,5.617929,1.313153,0.472694,30.040545,31.827914,...,1.943434,0.336582,3.362063,0.218080,0.335296,0.0,76.627252,1.760308,3.866473,20.446607
min,97.000000,67.000000,60.000000,12.000000,4.050000,65.000000,0.000000,37.000000,4.000000,20.000000,...,39.000000,5.000000,0.000000,0.200000,0.500000,1.0,50.400000,0.500000,30.200000,10.000000
25%,114.000000,77.000000,72.000000,13.000000,75.100000,70.300000,1.000000,37.300000,20.300000,55.600000,...,40.900000,5.827273,8.350000,0.744444,1.342857,1.0,326.686364,1.600000,36.750000,19.200000
50%,120.000000,80.000000,80.000000,14.000000,82.700000,75.000000,2.000000,37.600000,68.000000,80.200000,...,42.500000,6.000000,9.988194,0.850000,1.500000,1.0,346.328571,2.600000,39.500000,26.300000
75%,127.000000,83.000000,88.000000,15.000000,90.500000,79.800000,3.000000,37.800000,79.500000,104.451136,...,44.100000,6.166667,11.640341,0.957143,1.681364,1.0,362.935417,3.700000,42.350000,53.800000
max,201.000000,121.000000,100.000000,16.000000,198.800000,85.000000,10.000000,39.400000,150.000000,140.000000,...,46.000000,7.000000,20.000000,1.500000,2.500000,1.0,450.000000,7.700000,48.800000,84.000000

In [178]:
frames_t = [SBP_table_t, DBP_t, HR_t, RR_t, Weight_t, Oxygen_t ,Pain_t, Temperature_t, Glomerular_t,
            Alkaline_t, Alanine_t,
            Albumin_t, Aspartate_t, Protein_t, Bilirubin_t, Hemoglobin_t, MCV_t, MCHC_t, 
            Platelets_t, MCH_t, Hematocrit_t,
            Leukocytes_t, Erythrocytes_t, Carbon_t, Calcium_t, Chloride_t, Potassium_t, Urea_t, 
            Creatinine_t, Sodium_t,
            Glucose_t, Height_t, BMI_t, Low_Density_Cholesterol_t, High_Density_Cholesterol_t,
            Triglycerides_t, Total_Cholesterol_t, 
            Hemoglobin_t,
            Weight_difference_t, Microalbumin_t,
            GFR_t, DALY_t, QOLS_t, QALY_t, Globulin_t, Platelet_mean_t, Platelet_distribution_t,
            Erythrocyte_t, pH_Urine_t, Ketones_t, BilirubinMass_t, Glucose_Mass_t, Specific_gravity_t,
            Protein_MassUrine_t,
            ProstateAg_t, Left_ventricular_t, FEV1_FVC_t]

frames_t

Observations_t = pd.concat(frames_t, axis=1, sort=True)
Observations_t['Id'] = Observations_t.index
Observations_t.describe()

,Systolic Blood Pressure,Diastolic Blood Pressure,Heart rate,Respiratory rate,Body Weight,Oxygen saturation in Arterial blood,Pain severity - 0-10 verbal numeric rating [Score] - Reported,Body temperature,Glomerular filtration rate/1.73 sq M.predicted,Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma,...,Erythrocyte distribution width [Entitic volume] by Automated count,pH of Urine by Test strip,Ketones [Mass/volume] in Urine by Test strip,Bilirubin.total [Mass/volume] in Urine by Test strip,Glucose [Mass/volume] in Urine by Test strip,Specific gravity of Urine by Test strip,Protein [Mass/volume] in Urine by Test strip,Prostate specific Ag [Mass/volume] in Serum or Plasma,Left ventricular Ejection fraction,FEV1/FVC
count,19970.000000,19970.000000,19962.000000,19962.000000,19962.000000,1715.000000,20185.000000,1471.000000,5956.000000,5854.000000,...,4488.000000,941.000000,941.000000,941.000000,941.000000,941.0,941.000000,2432.000000,1379.000000,1141.000000
mean,122.254564,80.850010,79.970190,13.992644,82.022438,75.088722,2.167902,37.614933,54.525041,80.557724,...,42.512886,5.988535,10.143554,0.856178,1.485304,1.0,324.429199,2.850740,39.448441,36.226126
std,14.230206,7.180443,10.340307,1.031552,14.420766,5.743663,1.302540,0.450971,29.908927,31.965892,...,1.969283,0.332759,3.417865,0.228999,0.332263,0.0,81.284064,1.742951,3.881765,20.629652
min,98.000000,67.000000,60.000000,12.000000,3.950000,65.000000,0.000000,37.000000,4.000000,20.000000,...,39.000000,5.000000,0.100000,0.200000,0.500000,1.0,51.500000,0.500000,30.650000,10.000000
25%,114.000000,77.000000,72.000000,13.000000,74.800000,70.200000,1.000000,37.300000,20.262500,55.700000,...,40.800000,5.814286,8.370000,0.741667,1.314286,1.0,327.042857,1.500000,36.700000,19.000000
50%,120.000000,80.000000,80.000000,14.000000,82.600000,75.200000,2.000000,37.600000,68.500000,80.200000,...,42.521591,6.000000,10.041667,0.858333,1.485714,1.0,345.725000,2.600000,39.450000,27.200000
75%,127.000000,83.000000,88.000000,15.000000,90.500000,80.100000,3.000000,37.800000,79.300000,105.575000,...,44.100000,6.160000,11.825000,0.966667,1.663636,1.0,362.116667,3.600000,42.300000,55.500000
max,200.000000,121.500000,100.000000,16.000000,156.000000,85.000000,10.000000,39.400000,147.500000,140.000000,...,46.000000,7.000000,19.900000,1.500000,2.500000,1.0,448.900000,7.700000,48.750000,80.200000

In [179]:
Smoking, Smoking_t = Get_observations_categorical('Tobacco smoking status NHIS')

In [180]:
HIV, HIV_t = Get_observations_categorical('HIV status')

In [181]:
Cause_Death, Cause_Death_t = Get_observations_categorical('Cause of Death [US Standard Certificate of Death]')

In [182]:
## BilirubinPresence, BilirubinPresence_t = Get_observations_categorical('Bilirubin.total [Presence] in Urine by Test strip')
# Appearance_urine, Appearance_urine_t = Get_observations_categorical('Appearance of Urine')
### Leukocyte, Leukocyte_t = Get_observations_categorical('Leukocyte esterase [Presence] in Urine by Test strip')
###Nitrite, Nitrite_t = Get_observations_categorical('Nitrite [Presence] in Urine by Test strip')
###Glucose_Presence, Glucose_Presence_t = Get_observations_categorical('Glucose [Presence] in Urine by Test strip')
### Cause_Death, Cause_Death_t = Get_observations_categorical('Cause of Death [US Standard Certificate of Death]')

In [183]:
#Non numeric observations


Protein_urine, Protein_urine_t = Get_observations_categorical('Protein [Presence] in Urine by Test strip')
ClarityUrine, ClarityUrine_t = Get_observations_categorical('Clarity of Urine')
Odor, Odor_t = Get_observations_categorical('Odor of Urine')
Hemoglobin, Hemoglobin_t = Get_observations_categorical('Hemoglobin [Presence] in Urine by Test strip')
Color_Urine, Color_Urine_t = Get_observations_categorical('Color of Urine')
Ketones_Presence, Ketones_Presence_t = Get_observations_categorical('Ketones [Presence] in Urine by Test strip')
PhysicalProstate, PhysicalProstate_t= Get_observations_categorical('Physical findings of Prostate')

In [184]:
PhysicalProstate, PhysicalProstate_t= Get_observations_categorical('Physical findings of Prostate')

In [185]:
frames = [Smoking, HIV, Protein_urine, ClarityUrine, Odor, Hemoglobin, Color_Urine, Ketones_Presence,
          PhysicalProstate]

frames

Observations_Cat = pd.concat(frames, axis=1, sort=True)
Observations_Cat['Id'] = Observations_Cat.index
Observations_Cat.describe()

VALUE,Current every day smoker,Former smoker,Never smoker,HIV positive,not HIV positive,Urine protein test = + (finding),Urine protein test = ++ (finding),Urine protein test = +++ (finding),Cloudy urine (finding),Translucent (qualifier value),...,Blood in urine (finding),Urine blood test = negative (finding),Brown color (qualifier value),Reddish color urine,Urine ketone test = + (finding),Urine ketone test = ++ (finding),Urine ketone test = +++ (finding),Urine ketone test = trace (finding),Normal size prostate,Prostate enlarged on PR
count,79114.000000,79114.000000,79114.000000,190.000000,190.000000,3950.000000,3950.000000,3950.000000,3950.000000,3950.000000,...,3950.000000,3950.000000,3950.000000,3950.000000,3950.000000,3950.000000,3950.000000,3950.000000,9722.000000,9722.000000
mean,0.001188,0.746290,1.270192,0.347368,2.021053,0.111646,0.014937,7.244051,0.358481,7.012152,...,0.358481,7.012152,7.012152,0.358481,0.014684,0.000253,7.244051,0.111646,0.401666,0.598334
std,0.035176,1.636556,1.871885,0.967935,1.425237,0.384481,0.145950,4.948833,0.671828,5.209353,...,0.671828,5.209353,5.209353,0.671828,0.145105,0.015911,4.948833,0.384481,0.490260,0.490260
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,1.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,7.000000,0.000000,7.000000,...,0.000000,7.000000,7.000000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.000000
75%,0.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,12.000000,0.000000,12.000000,...,0.000000,12.000000,12.000000,0.000000,0.000000,0.000000,12.000000,0.000000,1.000000,1.000000
max,2.000000,16.000000,16.000000,5.000000,7.000000,2.000000,2.000000,27.000000,2.000000,27.000000,...,2.000000,27.000000,27.000000,2.000000,2.000000,1.000000,27.000000,2.000000,1.000000,1.000000

In [186]:
frames_t = [Smoking_t, HIV_t, Protein_urine_t, ClarityUrine_t, Odor_t, Hemoglobin_t, Color_Urine_t, Ketones_Presence_t,
            PhysicalProstate_t]

frames_t

Observations_Cat_t = pd.concat(frames_t, axis=1, sort=True)
Observations_Cat_t['Id'] = Observations_Cat_t.index
Observations_Cat_t.describe()

VALUE,Current every day smoker,Former smoker,Never smoker,HIV positive,not HIV positive,Urine protein test = + (finding),Urine protein test = ++ (finding),Urine protein test = +++ (finding),Cloudy urine (finding),Translucent (qualifier value),...,Blood in urine (finding),Urine blood test = negative (finding),Brown color (qualifier value),Reddish color urine,Urine ketone test = + (finding),Urine ketone test = ++ (finding),Urine ketone test = +++ (finding),Urine ketone test = trace (finding),Normal size prostate,Prostate enlarged on PR
count,19962.000000,19962.000000,19962.000000,60.000000,60.000000,941.000000,941.000000,941.000000,941.000000,941.000000,...,941.000000,941.000000,941.000000,941.000000,941.000000,941.000000,941.000000,941.000000,2432.000000,2432.000000
mean,0.001403,0.749825,1.253882,0.616667,2.250000,0.123273,0.018066,7.036132,0.352816,6.824655,...,0.352816,6.824655,6.824655,0.352816,0.014878,0.003188,7.036132,0.123273,0.409951,0.590049
std,0.038742,1.642984,1.864791,1.341536,2.088102,0.401725,0.148370,4.852809,0.683284,5.086702,...,0.683284,5.086702,5.086702,0.683284,0.129614,0.072863,4.852809,0.401725,0.491925,0.491925
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,1.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,1.500000,0.000000,0.000000,7.000000,0.000000,7.000000,...,0.000000,7.000000,7.000000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.000000
75%,0.000000,1.000000,1.000000,0.250000,4.000000,0.000000,0.000000,12.000000,0.000000,12.000000,...,0.000000,12.000000,12.000000,0.000000,0.000000,0.000000,12.000000,0.000000,1.000000,1.000000
max,2.000000,16.000000,17.000000,6.000000,8.000000,3.000000,2.000000,24.000000,2.000000,24.000000,...,2.000000,24.000000,24.000000,2.000000,2.000000,2.000000,24.000000,3.000000,1.000000,1.000000

In [187]:
Observations_Cat.shape

(79506, 23)

In [188]:
Observations_Cat_t.shape

(20051, 23)

## Organizations

In [189]:
#Not used for now

In [193]:
len(set(organizations.Id))

9218

## Patients

In [194]:
patients['BIRTHDATE'] = pd.to_datetime(patients.BIRTHDATE)
patients_t['BIRTHDATE'] = pd.to_datetime(patients_t.BIRTHDATE)

In [195]:
patients['DEATHDATE'] = pd.to_datetime(patients.DEATHDATE) 
patients_t['DEATHDATE'] = pd.to_datetime(patients_t.DEATHDATE)

In [196]:
patients.shape

(117959, 25)

In [197]:
patients_t.shape

(29492, 25)

In [198]:
#Function to calculate the age. If the patient is death calculate age at death. 
#If there's no date of death, set the date to June 5 2020

In [199]:
def calculateAge(birthDate, deathdate): 
    today = date(2020, 6, 5)
    if pd.isna(deathdate)==False: 
        today = deathdate
    
    age = today.year - birthDate.year - ((today.month, today.day) < 
         (birthDate.month, birthDate.day)) 
  
    return age

In [200]:
result = map(calculateAge, patients['BIRTHDATE'], patients['DEATHDATE'])

In [201]:
patients['Age'] = list(result)

In [202]:
result_t = map(calculateAge, patients_t['BIRTHDATE'], patients_t['DEATHDATE'])

In [203]:
patients_t['Age'] = list(result_t)

In [204]:
#Convert to dummy if the patient has a drivers licence
patients['DRIVERS'] = ~pd.isna(patients.DRIVERS) *1
patients_t['DRIVERS'] = ~pd.isna(patients_t.DRIVERS) *1

In [205]:
#Convert to dummy if the patient has a passport
patients['PASSPORT'] = ~pd.isna(patients.PASSPORT) *1
patients_t['PASSPORT'] = ~pd.isna(patients_t.PASSPORT) *1

In [206]:
patients['PLACE_BIRTH'] = [patient[-2:] for patient in patients.BIRTHPLACE]
patients_t['PLACE_BIRTH'] = [patient[-2:] for patient in patients_t.BIRTHPLACE]

In [207]:
patients.STATE.value_counts()

Massachusetts    117959
Name: STATE, dtype: int64

In [208]:
patients_t.STATE.value_counts()

Massachusetts    29492
Name: STATE, dtype: int64

In [210]:
patients.Age.describe()

count    117959.000000
mean         55.384600
std          18.783242
min           0.000000
25%          40.000000
50%          59.000000
75%          71.000000
max          84.000000
Name: Age, dtype: float64

In [211]:
patients_t.Age.describe()

count    29492.00000
mean        55.33426
std         18.95706
min          0.00000
25%         41.00000
50%         59.00000
75%         71.00000
max         84.00000
Name: Age, dtype: float64

In [212]:
#ask why children

## Payers

In [213]:
#Not used for now

In [215]:
payers.NAME.value_counts()

NO_INSURANCE              1
Humana                    1
UnitedHealthcare          1
Medicare                  1
Aetna                     1
Medicaid                  1
Blue Cross Blue Shield    1
Anthem                    1
Dual Eligible             1
Cigna Health              1
Name: NAME, dtype: int64

Aggregate of all plans

## Payer transitions

In [216]:
#Not used for now

## Procedures

In [219]:
options = np.setdiff1d(list(set(procedures.DESCRIPTION)), list(set(procedures_t.DESCRIPTION)))
options

array(['Admission to neurosurgical department', 'Asthma screening',
       'Lung Transplant', 'negative screening for PHQ9'], dtype='<U105')

In [220]:
procedures_tmp = procedures.loc[~procedures.DESCRIPTION.isin(list(options))]

In [221]:
options = np.setdiff1d(list(set(procedures_t.DESCRIPTION)), list(set(procedures.DESCRIPTION)))
options

array([], dtype='<U105')

In [222]:
options = np.setdiff1d(list(set(procedures.REASONDESCRIPTION)), list(set(procedures_t.REASONDESCRIPTION)))
options

array(['Asthma', 'Attempted suicide - cut/stab', 'Childhood asthma',
       'Cystic Fibrosis',
       'Fracture of the vertebral column with spinal cord injury',
       'Non-small cell carcinoma of lung  TNM stage 2 (disorder)'],
      dtype='<U69')

In [223]:
procedures_tmp = procedures_tmp.loc[~procedures_tmp.REASONDESCRIPTION.isin(list(options))]

In [224]:
Procedures = Pivot_table_counts(procedures_tmp)

In [225]:
Procedures_t = Pivot_table_counts(procedures_t)

In [226]:
ProceduresReason = Pivot_table_counts(procedures_tmp, 'REASONDESCRIPTION')

In [227]:
ProceduresReason_t = Pivot_table_counts(procedures_t, 'REASONDESCRIPTION')

In [228]:
Procedures.describe()

DESCRIPTION,Admission to burn unit,Admission to long stay hospital,Admission to orthopedic department,Admission to trauma surgery department,Allergy screening test,Alpha-fetoprotein test,Ankle X-ray,Antenatal RhD antibody screening,Appendectomy,Augmentation of labor,...,Urine culture,Urine protein test,Urine screening for glucose,Urine screening test for diabetes,Vaccination for diphtheria pertussis and tetanus,Vasectomy,X-ray or wrist,negative screening for depression on phq9,positive screening for PHQ-9,positive screening for depression on phq9
count,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,...,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000,73498.000000
mean,0.000204,0.000231,0.006817,0.000177,0.001456,0.021443,0.004367,0.003075,0.000830,0.002381,...,0.021851,0.021851,0.021824,0.021851,0.021824,0.000381,0.004191,0.000150,0.000095,0.000095
std,0.014285,0.015207,0.082281,0.013298,0.041214,0.144856,0.065943,0.055367,0.028797,0.048738,...,0.146384,0.146384,0.146109,0.146384,0.146109,0.019515,0.064599,0.012233,0.009759,0.014286
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000

In [229]:
ProceduresReason_t.describe()

REASONDESCRIPTION,Acute bronchitis (disorder),Acute viral pharyngitis (disorder),Appendicitis,Atrial Fibrillation,Bullet wound,Cardiac Arrest,Child attention deficit disorder,Chronic obstructive bronchitis (disorder),Closed fracture of hip,Facial laceration,...,Pulmonary emphysema (disorder),Recurrent rectal polyp,Rupture of patellar tendon,Secondary malignant neoplasm of colon,Streptococcal sore throat (disorder),Stroke,Suicidal deliberate poisoning,Suspected lung cancer (situation),Third degree burn,Tubal pregnancy
count,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,...,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000,8741.000000
mean,0.095412,0.025626,0.001258,0.708500,0.000343,0.078938,0.005263,0.211303,0.004805,0.009610,...,0.256836,0.006521,0.001258,0.000343,0.016131,0.099531,0.000343,0.045533,0.001602,0.000343
std,0.295741,0.158027,0.035454,3.307665,0.018524,0.480219,0.223289,1.349494,0.085437,0.110746,...,1.527640,0.080494,0.035454,0.032088,0.126891,0.435996,0.032088,0.363664,0.056578,0.018524
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.000000,1.000000,1.000000,45.000000,1.000000,3.000000,11.000000,24.000000,2.000000,2.000000,...,22.000000,1.000000,1.000000,3.000000,2.000000,4.000000,3.000000,3.000000,2.000000,1.000000

In [230]:
del procedures_tmp, procedures_t

## Providers

In [231]:
#Not used for now

In [233]:
providers.shape

(60968, 12)

## Supplies

In [234]:
#Not used for now as it doesn't exist in test set - confirmed by team not useful

In [235]:
#supplies.head()

# Merge Tables

## Tables in the train dataset

In [236]:
#Define how to fill missing

In [237]:
train = pd.merge(patients, Allergies,  on='Id', how='left')

In [238]:
train = pd.merge(train, Careplans,  on='Id', how='left')

In [239]:
train = pd.merge(train, Careplans_reason,  on='Id', how='left')

In [240]:
train = pd.merge(train, Conditions,  on='Id', how='left')

In [241]:
train = pd.merge(train, Devices,  on='Id', how='left') 

#Negative for non presence as opposed to missing

train['Coronary artery stent (physical object)'] = train['Coronary artery stent (physical object)'].fillna(0)
train['Implantable cardiac pacemaker (physical object)'] = train['Implantable cardiac pacemaker (physical object)'].fillna(0)
train['Implantable defibrillator  device (physical object)'] = train['Implantable defibrillator  device (physical object)'].fillna(0)

In [242]:
train = pd.merge(train, Encounters,  on='Id', how='left')

In [243]:
train = pd.merge(train, Encounters_reason,  on='Id', how='left')

In [244]:
train = pd.merge(train, Imaging_studies,  on='Id', how='left')

In [245]:
train = pd.merge(train, Imaging_studies_mod,  on='Id', how='left')

In [246]:
train = pd.merge(train, Immunizations,  on='Id', how='left')

In [247]:
train = pd.merge(train, Medications,  on='Id', how='left')

In [248]:
#Observations
train = pd.merge(train, Observations,  on='Id', how='left')

In [249]:
train = pd.merge(train, Observations_Cat,  on='Id', how='left')

In [250]:
train = pd.merge(train, Procedures,  on='Id', how='left')

In [251]:
train = pd.merge(train, ProceduresReason,  on='Id', how='left')

In [252]:
train.shape

(117959, 953)

In [253]:
train.shape

(117959, 953)

## Tables in the Test Dataset

In [254]:
test = pd.merge(patients_t, Allergies_t,  on='Id', how='left')

In [255]:
test = pd.merge(test, Careplans_t,  on='Id', how='left')

In [256]:
test = pd.merge(test, Careplans_reason_t,  on='Id', how='left')

In [257]:
test = pd.merge(test, Conditions_t,  on='Id', how='left')

In [258]:
test = pd.merge(test, Devices_t,  on='Id', how='left')

#Negative for non presence as opposed to missing

test['Coronary artery stent (physical object)'] = test['Coronary artery stent (physical object)'].fillna(0)
test['Implantable cardiac pacemaker (physical object)'] = test['Implantable cardiac pacemaker (physical object)'].fillna(0)
test['Implantable defibrillator  device (physical object)'] = test['Implantable defibrillator  device (physical object)'].fillna(0)

In [259]:
test = pd.merge(test, Encounters_t,  on='Id', how='left')

In [260]:
test = pd.merge(test, Encounters_reason_t,  on='Id', how='left')

In [261]:
test = pd.merge(test, Imaging_studies_t,  on='Id', how='left')

In [262]:
test = pd.merge(test, Imaging_studies_mod_t,  on='Id', how='left')

In [263]:
test = pd.merge(test, Immunizations_t,  on='Id', how='left')

In [264]:
test = pd.merge(test, Medications_t,  on='Id', how='left')

In [265]:
test = pd.merge(test, Observations_t,  on='Id', how='left')

In [266]:
test = pd.merge(test, Observations_Cat_t,  on='Id', how='left')

In [267]:
test = pd.merge(test, Procedures_t,  on='Id', how='left')

In [268]:
test = pd.merge(test, ProceduresReason_t,  on='Id', how='left')

In [269]:
test.shape

(29492, 953)

In [270]:
test.shape

(29492, 953)

## COVID Status

In [271]:
conditions = pd.read_csv(TRAIN + 'conditions.csv')

In [272]:
observations = pd.read_csv(TRAIN + 'observations.csv')

In [273]:
CoVID_status = pd.DataFrame()

In [274]:
#identify patients diagnosed with COVID-19
covid_patient_ids = conditions[conditions.CODE==840539006].PATIENT.unique()

In [275]:
COVID_Positive = pd.DataFrame({'Id' : covid_patient_ids, 'COVID_Status' : 1})

In [276]:
patient_ids = patients.Id.unique()
len(patient_ids)

117959

In [277]:
len(covid_patient_ids) 
#The database has 73697 patients positive for COVID-19

73697

In [278]:
observations[(observations.CODE == '94531-1')].VALUE.value_counts()

Detected (qualifier value)        73697
Not detected (qualifier value)    31851
Name: VALUE, dtype: int64

In [279]:
len(observations[(observations.CODE == '94531-1')].PATIENT.unique())

75417

In [280]:
covid_patient_ids = observations[(observations.CODE == '94531-1') &
                        (observations.VALUE == 'Detected (qualifier value)')].PATIENT.unique()

In [281]:
len(covid_patient_ids)

73697

In [282]:
#identify patients with a negative SARS-CoV-2 test - this list may not be good as some patients overalp
negative_covid_patient_ids = observations[(observations.CODE == '94531-1') &
                        (observations.VALUE == 'Not detected (qualifier value)')].PATIENT.unique()

In [283]:
len(negative_covid_patient_ids)

16787

In [284]:
#in both lists

both = [x for x in covid_patient_ids.tolist() if x in negative_covid_patient_ids.tolist()]
len(both)

15067

In [285]:
#Definition 1: Patient has a negative covid test

In [286]:
negative_covid_patient = [x for x in negative_covid_patient_ids.tolist() if x not in covid_patient_ids.tolist()]

In [287]:
len(negative_covid_patient)

1720

In [288]:
#Definition 2: Patient is negative if no covid test

In [289]:
negative_covid_patient = [x for x in patient_ids.tolist() if x not in covid_patient_ids.tolist()]

In [290]:
len(negative_covid_patient)

44262

In [291]:
COVID_Negative = pd.DataFrame({'Id' : negative_covid_patient, 'COVID_Status' : 0})

In [292]:
CoVID_status = pd.concat([COVID_Positive, COVID_Negative], axis=0)

In [293]:
len(CoVID_status.Id.unique())

117959

In [294]:
del COVID_Positive, COVID_Negative

In [295]:
CoVID_status.shape

(117959, 2)

In [296]:
len(negative_covid_patient_ids)

16787

In [297]:
No_test = [p for p in patients.Id.tolist() if p not in list(covid_patient_ids) + list(negative_covid_patient)]

In [298]:
len(No_test)

0

In [299]:
#No_test = pd.DataFrame({'Id' : No_test, 'No_test' : 1})

In [300]:
#Patients in train without COVID test
#train_no_test = pd.merge(train, No_test,  on='Id', how='right')
#train_no_test.shape

In [301]:
#Main Table

train = pd.merge(train, CoVID_status,  on='Id', how='right')
train.shape

(117959, 954)

In [302]:
del CoVID_status

## Death due to COVID status

In [303]:
covid_patient_ids

array(['afa2680f-7f73-46d9-b0cd-2cf3db49724b',
       '26e5d262-6cdc-4274-a5cd-d7fd439e35f9',
       '90031c21-e8a4-416e-b60b-23e871ee62dc', ...,
       '8722685f-ce37-4520-ab95-22b6929526c2',
       '62e3e406-8375-4cf5-aae7-0d489e40e73c',
       '18b4b304-dddd-41e8-a13d-08a3285552be'], dtype=object)

In [304]:
#Calculate death status
deceased_ids = np.intersect1d(covid_patient_ids, patients[patients.DEATHDATE.notna()].Id)

In [305]:
len(deceased_ids)

5568

In [306]:
DeceasedDB = pd.DataFrame({'Id': deceased_ids, 'Death': 1})

In [307]:
DeceasedDB.shape

(5568, 2)

In [308]:
train = pd.merge(train, DeceasedDB,  on='Id', how='left')

In [309]:
train.shape

(117959, 955)

In [310]:
del DeceasedDB

In [311]:
train['Death'] = train.Death.fillna(0)

In [313]:
train.COVID_Status.describe()

count    117959.000000
mean          0.624768
std           0.484185
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: COVID_Status, dtype: float64

In [314]:
train.Death.describe()

count    117959.000000
mean          0.047203
std           0.212073
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Death, dtype: float64

## Hospitalized COVID patients

In [315]:
encounters = pd.read_csv(TRAIN + 'encounters.csv')

In [316]:
encounters['START'] = pd.to_datetime(encounters.START)

In [317]:
encounters['STOP'] = pd.to_datetime(encounters.STOP)

In [318]:
encounters['Days_hospitalized'] = encounters.STOP  - encounters.START

In [319]:
inpatient_ids = encounters[(encounters.REASONCODE == 840539006) & (encounters.CODE == 1505002)].PATIENT

In [320]:
LOS_hospital = encounters[(encounters.REASONCODE == 840539006) & (encounters.CODE == 1505002)].Days_hospitalized

In [321]:
Hospitalized = pd.DataFrame({'Id': inpatient_ids,
                             'Days_hospitalized': LOS_hospital,
                             'Hospitalized': 1})

In [322]:
train = pd.merge(train, Hospitalized,  on='Id', how='left')

In [323]:
train['Hospitalized'] = train.Hospitalized.fillna(0)

In [324]:
del Hospitalized

In [325]:
train.shape

(117959, 957)

## Ventilated COVID

In [326]:
procedures = pd.read_csv(TRAIN + 'procedures.csv')

In [327]:
vent_ids = procedures[(procedures.CODE == 26763009) & (procedures.PATIENT.isin(covid_patient_ids))].PATIENT.unique()

In [328]:
len(vent_ids)

4210

In [329]:
Ventilator = pd.DataFrame({'Id': vent_ids, 'Ventilator': 1})

In [331]:
Ventilator.shape

(4210, 2)

In [332]:
train = pd.merge(train, Ventilator, on='Id', how='left')

In [333]:
train['Ventilator'] = train.Ventilator.fillna(0)

In [334]:
del Ventilator

## ICU COVID

In [335]:
icu_ids = encounters[(encounters.CODE == 305351004) &(encounters.PATIENT.isin(covid_patient_ids))].PATIENT.unique()

In [336]:
len(icu_ids)

4981

In [337]:
LOS_ICU = encounters[(encounters.CODE == 305351004) &(encounters.PATIENT.isin(covid_patient_ids))].Days_hospitalized

In [338]:
ICU = pd.DataFrame({'Id': icu_ids, 'Days_ICU': LOS_ICU, 'ICU': 1})

In [339]:
train = pd.merge(train, ICU,  on='Id', how='left')

In [340]:
train['ICU'] = train.ICU.fillna(0)

In [341]:
del ICU

In [343]:
train.shape

(117959, 960)

# Export File for analysis

In [344]:
#'Encounter for symptom (procedure)' and 'Acute respiratory failure (disorder)_x',
#Were removed from the dataset
#We removed 'CITY', 'ZIP' because we have latitude and longitude


drop = ['SSN', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'ADDRESS',
       'BIRTHDATE', 'DEATHDATE', 'BIRTHPLACE', 'STATE',
       'Encounter for symptom (procedure)', 
       'Acute respiratory failure (disorder)_x', 'CITY', 'ZIP']
train.drop(columns = drop, inplace=True)

In [345]:
#Convert time to days

In [346]:
train['Days_hospitalized'] = train['Days_hospitalized'] / np.timedelta64(1, 'D')

In [347]:
train['Days_ICU'] = train['Days_ICU'] / np.timedelta64(1, 'D')

#Drop columns that have little to no information


train.dtypes

In [348]:
train.to_csv('train.csv', index=False)

In [349]:
test.drop(columns=drop, inplace=True)

In [350]:
test.to_csv('test.csv', index=False)

In [352]:
#train covid only for the models

train_no_test.drop(columns = drop, inplace=True)
train_no_test.to_csv('train_no_test.csv', index=False)